### ISSUE TITLE
Convert_data2mnc

### ISSUE THREAD

**Issue by shshiva** [neuropoly/template#1]
Issue arises when running "preprocessing.py" script.
--> Traceback(most recent call last):
       file "preprocessing.py, line 734, in <module>
          convert_data2mnc(dataset_info,contrast='t2')
       file "preprocessing.py, line 675, in convert_data2mnc
          path_template_mask=create_mask_template(data_info,contrast),...

<img width="370" alt="convert to minc error" src="https://user-images.githubusercontent.com/39805011/40796134-1053148a-64d2-11e8-9915-ef948d950184.png">

  ~Shiva

**Comment by benjamindeleener** [comment]
Hi Shiva, sorry for the late answer.

I don't know exactly what could cause the issue. Could you try the following command (when being in the correct template folder) and copy-paste here the result? Also, check if the file `template_mask.nii.gz` was created in the first place.

```
nii2mnc template_mask.nii.gz template_mask.mnc
```

If the file was not created, we should check above what happened, but the issue could also come from `nii2mnc` itself. I also noticed that you might not be using the latest version of the script (line number are not the same as in https://github.com/neuropoly/template/blob/master/preprocessing.py)

**Comment by shshiva** [comment]
Hi Benjamin, 
No problem at all. Thanks for writing back.
Actually I tried to source the environment to minc(1.9.16) and it worked! I could convert nifti files to mnc after sourcing.
And yes I have both template_mask.nii.gz and template_mask.mnc under template folder.
I am in process of generating the new template, and will update you on progress.

Thanks,
~Shiva
