### ISSUE TITLE
Format with 'tree' structure and use proper formatting

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/template#17]
here:

![image](https://user-images.githubusercontent.com/2482071/234643817-e83a60a3-6b30-4c98-be24-743c179b9048.png)

from this branch:
https://github.com/neuropoly/template/tree/nb/updated_all

pls use formatting like here:
https://ivadomed.org/data.html

**Comment by jcohenadad** [comment]
Change "data_type" for "anat"

**Comment by jcohenadad** [comment]
"'sub-101' + suffix_image + suffix_label-disc + '-manual.nii.gz' "
I would remove the "manual"-- for this template workflow, we can assume that ppl know how to get organized-- and a label, if it exists, is a correct label, regardless how it was created

**Comment by rohanbanerjee** [comment]
This issue is solved in this commit here: https://github.com/neuropoly/template/commit/77a166b3f7406dd16abff030d5e08fc8edf4f844. Closing this issue therefore.
