### ISSUE TITLE
Issue while straightening spinal cord

### ISSUE THREAD

**Issue by rohanbanerjee** [neuropoly/template#22]
Hello,

I am currently using `sct version: 5.8` and the branch `nb/updated_all`
I am facing the following error when the template generation pipeline reaches the straighten spinal cord step:

```
Traceback (most recent call last):
  File "/Users/rohanbanerjee/sct_5.8/spinalcordtoolbox/scripts/sct_straighten_spinalcord.py", line 280, in <module>
    main(sys.argv[1:])
  File "/Users/rohanbanerjee/sct_5.8/spinalcordtoolbox/scripts/sct_straighten_spinalcord.py", line 263, in main
    fname_straight = sc_straight.straighten()
  File "/Users/rohanbanerjee/sct_5.8/spinalcordtoolbox/straightening.py", line 387, in straighten
    idx_closest = centerline_straight.get_closest_to_absolute_position(disc_label, relative_position,
  File "/Users/rohanbanerjee/sct_5.8/spinalcordtoolbox/types.py", line 629, in get_closest_to_absolute_position
    relative_position_from_reference_backup = backup_centerline.dist_points[backup_index] - position_reference_backup
IndexError: list index out of range
```

### Short explanation

The template generation pipeline goes through multiple steps before the spinal cord straightening is carried out, namely, `generate_centerline`, `average_centerline` and `generate_initial_template_space`. The outputs from the first step look ok but I am suspecting that this issue is arising from the `average_centerline` step -- in calculating the distances from the `C1` step 

Both the subjects that I am using have the same number of vertebral level (26) so we can possibly rule out the issue being related to different sizes of the spinal cords of different subjects. I am currently debugging and would be updating this issue as comments. Any insights in the meantime would be helpful.

**Comment by rohanbanerjee** [comment]
Investigating this issue, further along with @benjamindeleener ,

A few observations,

The values which `centerline.distance_from_C1label` produces doesn't seem to be right. For example, from this [line](https://github.com/neuropoly/template/blob/86ed4903dbbe5d830c45a06a238436244e75375a/template_preprocessing.py#L247) which is a part of the `average_centerline` method, I get the following values,

> [{'C1': 0.0, 'C2': 25.093314046832084, 'C3': 62.41383470221325, 'C4': 71.66655107904904, 'C5': 71.66655107904904, 'C6': 71.66655107904904, 'C7': 71.66655107904904, 'T1': 71.66655107904904, 'T2': 71.66655107904904, 'T3': 71.66655107904904, 'T4': 71.66655107904904, 'T5': 71.66655107904904, 'T6': 71.66655107904904, 'T7': 71.66655107904904, 'T8': 71.66655107904904, 'T9': 71.66655107904904, 'T10': 71.66655107904904, 'T11': 71.66655107904904, 'T12': 71.66655107904904, 'L1': 71.66655107904904, 'L2': 71.66655107904904, 'L3': 71.66655107904904, 'L4': 71.66655107904904}]

This in turn directly effects the size of the template_space that is being generated. To clarify,

Before the code was modified i.e. when I used [this](https://github.com/neuropoly/template/tree/rb/chnages_to_generate_centerline_method) branch to generate my template (which only had 23 discs), my `template_space` dimension was the below,


But now the `template_space` dimension is the below,

<img width="321" alt="Screen Shot 2023-06-26 at 4 35 10 PM" src="https://github.com/neuropoly/template/assets/25586344/09ea2338-1286-4d3d-953b-7db50fb7edff">

**Comment by rohanbanerjee** [comment]
Solved the above issue by replacing the lines [159](https://github.com/neuropoly/template/blob/8a05d3f934d1bfb4279b73b8d4d3c5f9f2398e03/preprocessing.py#L159) to [165](https://github.com/neuropoly/template/blob/8a05d3f934d1bfb4279b73b8d4d3c5f9f2398e03/preprocessing.py#L165), with the old script line [159](https://github.com/neuropoly/template/blob/8a05d3f934d1bfb4279b73b8d4d3c5f9f2398e03/preprocessing.py#L159).

This produced the template space of:
<img width="321" alt="Screen Shot 2023-06-26 at 5 41 11 PM" src="https://github.com/neuropoly/template/assets/25586344/1415d0a1-6a23-46ac-986d-967e1530c1af">

and also successfully straightened the spinal cord. I'm now getting an error in the `normalize_intensity_template` in the line [570](https://github.com/neuropoly/template/blob/86ed4903dbbe5d830c45a06a238436244e75375a/template_preprocessing.py#L570). The error is the below:

```
File "/Users/rohanbanerjee/Documents/research/neuropoly/dog_template_updated/template/preprocessing.py", line 585, in normalize_intensity_template
    intensities.append(np.mean(image.data[coord_z[0] - extend - 1:coord_z[0] + extend, coord_z[1] - extend - 1:coord_z[1] + extend, coord_z[2]]))
IndexError: index 865 is out of bounds for axis 2 with size 865
```

Debugging this now

**Comment by NadiaBlostein** [comment]
Resolved if you use the right SCT commit (`git checkout COMMIT_VERSION_FROM_README`)

**Comment by rohanbanerjee** [comment]
This issue was resolved by changing the new version of `SCT`
