### ISSUE TITLE
Adding a configuration_default.json file which is git-tracked

### ISSUE THREAD

**Issue by rohanbanerjee** [neuropoly/template#28]
### Purpose
- There should be a` configuration_default.json` file which is git-tracked meaning updated with the latest changes. When a user wants to use the configuration files, they should copy the `configuration_default.json` and rename it as `configuration.json`.
- The `configuration.json` will be called in the code and values from it will be used for the `template_preprocessing_pipeline.py`.

Needs to be implemented in `nb/updated_all` branch

**Comment by NadiaBlostein** [comment]
`nb/updated_all` branch, commit `46c2c7a007610f341f68aa8b120866f804b7ad50`

**Comment by NadiaBlostein** [comment]
`nb/updated_all` branch, commit `46c2c7a007610f341f68aa8b120866f804b7ad50`
