### ISSUE TITLE
Remove `contrast` parameter in the `template_preprocessing.py` script

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/template#30]
TODO: We are mentioning the contrast in the configuration file and also in the method parameters. We should consider removing the parameter from the method parameters.

Here: https://github.com/neuropoly/template/blob/nb/updated_all/template_preprocessing.py

To implement in https://github.com/neuropoly/template/edit/nb/updated_all

**Comment by NadiaBlostein** [comment]
`nb/updated_all`, commit `0d18af4adf2bf351d50740275bbc88100692cc36`
