### ISSUE TITLE
Remove loading of npz for centerline

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/template#34]
Remove this:
https://github.com/neuropoly/template/blob/c68e903e77b0a13f931af53816875a29804b9003/template_preprocessing.py#L161-L165

because we just want to regenerate it all the time-- for reliability purpose

also, we don't need to save the npz, so remove:
https://github.com/neuropoly/template/blob/c68e903e77b0a13f931af53816875a29804b9003/template_preprocessing.py#L161-L165

**Comment by NadiaBlostein** [comment]
Fixed with PR #53 `nb/preprocess_segment`, last commit (`0ca0cd4b469cd99bf521a6ada765bc93b85adebf`)
