### ISSUE TITLE
Removal of redundancy in the suffix in the configuration file

### ISSUE THREAD

**Issue by rohanbanerjee** [neuropoly/template#36]
### Explanation:
The contrast name is not required in the suffix of the of configuration file like done here: https://github.com/neuropoly/template/blob/2c4883ac4dbcd474283d6f2b09763f31ad2281bc/configuration.json#L6C1-L6C1.

Instead should be changed like this: https://github.com/neuropoly/template/blob/2c4883ac4dbcd474283d6f2b09763f31ad2281bc/README.md?plain=1#L96

TODO:
The changes have to be made in the `nb/updated_all` branch.

**Comment by NadiaBlostein** [comment]
`nb/updated_all` branch, commit `46c2c7a007610f341f68aa8b120866f804b7ad50`
