### ISSUE TITLE
Merging template_preprocessing.py and template_preprocessing_pipeline.py into one file

### ISSUE THREAD

**Issue by rohanbanerjee** [neuropoly/template#40]
### Purpose
We should merge the `template_preprocessing.py` and `template_preprocessing_pipeline.py` into `template_preprocessing_pipeline.py`. Basically copy everything from  `template_preprocessing.py` into  `template_preprocessing_pipeline.py`.

**Comment by NadiaBlostein** [comment]
Branch `nb/updated_all`, commit `7448830817abd0d92b575c4e5ee4e41ec51698bf`
