### ISSUE TITLE
Take into account min and max disc label option from configuration file into code

### ISSUE THREAD

**Issue by NadiaBlostein** [neuropoly/template#41]
# Context

Currently, it is possible to specify the min/max of labels from the config file, see here:

https://github.com/neuropoly/template/blob/81e9d93763886f0d2e2610e1a0537d427ef2a166/configuration_default.json#L7-L8

What is missing though is: the ability to make use of the information entered in the config file.

# Solution

Modify the following files: https://github.com/neuropoly/template/blob/master/preprocess_normalize.py

**Comment by jcohenadad** [comment]
depends on #60

**Comment by NadiaBlostein** [comment]
We decided to only include `last_disc` in configuration.json! And `last_disc` part depends on issue #60, refer to that to see the fix.

**Comment by NadiaBlostein** [comment]
Fixed in branch `nb/issues_59_and_41`, commit `cd8b936faa31d5a1bba63b15937e20bc5a87b319`
