### ISSUE TITLE
Better document how to do manual QC and keep provenance of who did the QC

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/template#58]
this section: https://github.com/neuropoly/template/blob/25267b7268b0a4f6d986a0ff083dabcc5b469c8f/README.md#14-quality-control-qc-labels

there is now a good procedure put in place by @sandrinebedard and @valosekj (can you please cross-ref the script?)

**Comment by valosekj** [comment]
For the html QC report, we usually have repo-specific instructions for each project. For example, [here](https://github.com/ivadomed/canproco#3-manual-correction-of-spinal-cord-segmentation) for CanProCo project. 

Regarding manual corrections, we have [`manual-correction`](https://github.com/spinalcordtoolbox/manual-correction) repo. The repo contains the [`manual_correction.py`](https://github.com/spinalcordtoolbox/manual-correction/blob/main/manual_correction.py) script, which can be used for manual correction of spinal cord segmentation, disc labels, centerline etc. The repo also contains a [wiki](https://github.com/spinalcordtoolbox/manual-correction/wiki) with examples.

**Comment by valosekj** [comment]
Hmm, actually, on [spinalcordtoolbox.com](https://spinalcordtoolbox.com) web, we have [QC report section](https://spinalcordtoolbox.com/user_section/tutorials/analysis-pipelines-with-sct/inspecting-the-results.html#quality-control-report). We could extend this section by moving appropriate parts from the [CanProCo repo](https://github.com/ivadomed/canproco#3-manual-correction-of-spinal-cord-segmentation). Then, we could reference the updated QC report section across projects/repos.
