### ISSUE TITLE
msct_image does not exist in the newer versions of SCT

### ISSUE THREAD

**Issue by armaneshaghi** [neuropoly/template#6]
@jcohenadad @benjamindeleener
Has anyone managed to run the template scripts with the latest SCT? I get import error for `msct_image` which I think has been removed from SCT. 

Alternatively, does anyone know what version of SCT was used in the De Leneer et al (PAM 50) paper so I can probably get the template creation running with that (presumably old) version .

Thank you.

**Comment by jcohenadad** [comment]
@charleygros I think you ran this pipeline recently (with a recent version of SCT) and bumped into the same problem. Could you please share your tips? Thanks!

**Comment by armaneshaghi** [comment]
@jcohenadad thanks Julien. Even if the script is not working, I wonder whether the final results of the script and the registered ICBM (brain) data can be made available? What I mean is the "fused" brain and spine  shown in the Figure 4 of De Leneer et al.

**Comment by charleygros** [comment]
Dear @armaneshaghi,
Thank you for your feedback.
I should be able to push a new version of the pipeline which is compatible with the last release of SCT [here](https://github.com/neuropoly/spinalcordtoolbox/tree/v3.2.7).
Hope it will help. I keep you updated.

**Comment by charleygros** [comment]
@armaneshaghi: I have updated the processing script (see branch `master`) so that it is compatible with the SCT v3.2.4. and higher.
Please let me know if it helps. I remain at your disposal if needed.

**Comment by armaneshaghi** [comment]
Thank you @charleygros. It has improved significantly. 

When I try to run the `pipeline.py` with SCT's Python. 

```
Status:  20%|####################8                                                                                   | 1.00/5.00 [00:21<01:26, 21.6s/B]
Status: 100%|########################################################################################################| 5.00/5.00 [01:45<00:00, 21.0s/B]
Status: 100%|#########################################################################################################| 5.00/5.00 [15:38<00:00, 187s/B]
Status:   0%|                                                                                                               | 0.00/5.00 [00:00<?, ?B/s]
/mounts/auto/ipmsa/supertemplate/template/preprocessing.py:660: RuntimeWarning: divide by zero encountered in double_scalars
  image_image_new.data[:, :, i] *= average_intensity / intensity_profiles[subject_name][i]
/mounts/auto/ipmsa/supertemplate/template/preprocessing.py:660: RuntimeWarning: invalid value encountered in multiply
  image_image_new.data[:, :, i] *= average_intensity / intensity_profiles[subject_name][i]

Traceback (most recent call last):                                                                                   | 1.00/5.00 [00:01<00:07, 1.97s/B]
  File "template/pipeline.py", line 41, in <module>##################################################################| 5.00/5.00 [00:10<00:00, 2.13s/B]
    convert_data2mnc(dataset_info, contrast='t1')
  File "/mounts/auto/ipmsa/supertemplate/template/preprocessing.py", line 688, in convert_data2mnc
    path_template_mask = create_mask_template(dataset_info, contrast)
  File "/mounts/auto/ipmsa/supertemplate/template/preprocessing.py", line 679, in create_mask_template
    sct.run('nii2mnc ' + path_template + 'template_mask.nii.gz ' + ' ' + path_template + 'template_mask.mnc')
  File "/data/ipmsa/ipmsa/sct/scripts/sct_utils.py", line 476, in run
    raise RunError(output)
sct_utils.RunError: ** ERROR: nifti_image_read(/mounts/auto/ipmsa/supertemplate/data/template/template_mask.nii.gz): bad dim[0]
Segmentation fault (core dumped)
```

Any idea what to check next? I thought might be minc toolkit issue but that seems to have been installed.

**Comment by armaneshaghi** [comment]
Thanks again @charleygros . The last comment was related to minc toolkit and not SCT.
