### ISSUE TITLE
Subject straightening in `preprocess_normalize.py` requires either SC mask NIFTI file or centerline NIFTI file

### ISSUE THREAD

**Issue by NadiaBlostein** [neuropoly/template#68]
### Code
Master branch, `preprocess_normalize.py`

### Issue
Subject straightening in `preprocess_normalize.py` `straighten_all_subjects()` method requires either SC mask NIFTI file (`*_label-SC_mask.nii.gz`) or centerline NIFTI file (`*_label-centerline.nii.gz`) , [lines 476 to 491](https://github.com/neuropoly/template/blob/5f511c763d72405a6ed21f5fd31979b7a4dd5dcb/preprocess_normalize.py#L476C1-L491C44). 

Currently, the `generate_centerline()` method generates centerlines for every subject, whether they have a SC mask or not. However, this method does not save the centerline files in NIFTI format. Therefore,   `straighten_all_subjects()` method throws an error for subjects that do not have a SC mask in NIFTI file.

### Solution

1) If the subject does not have a SC mask NIFTI file (`*_label-SC_mask.nii.gz`), check if it has a centerline NIFTI file (`*_label-centerline.nii.gz`) and use that instead.
2) If the subject does not have a SC mask NIFTI file (`*_label-SC_mask.nii.gz`) or a centerline NIFTI file (`*_label-centerline.nii.gz`), generate subject centerline and save the centerline NIFTI file (`*_label-centerline.nii.gz`).

**Comment by rohanbanerjee** [comment]
This issue is solved by merging #69 . Closing it therefore.
