### ISSUE TITLE
Consider moving hard-coded information in project-specific config files

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/template#7]
This code:

https://github.com/neuropoly/template/blob/62f0c8e5edaa63d1674a526b55577ceb4325454a/preprocessing.py#L16-L42

Is specific to the PAM50 template. As other projects are deriving from this repository, we should consider making the code more modular and create config files.

**Comment by rohanbanerjee** [comment]
We now use config files for the pipeline and the pipeline overall is more modular. The specific values to the PAM50 template mentioned in the above comment are also removed. Closing this issue therefore.
